### ISSUE TITLE
General tidy-up actions before launch

### ISSUE THREAD

**Issue by agully1** [ca-knowledgebase/ca-knowledgebase.github.io#104]
- [x] Remove/edit admonitions
- [x] Remove all references to site being 'in alpha' or similar
- [x] Edit 'content will be added soon' messages where relevant
- [x] Add TOCs to all header pages (e.g. tutorials)
- [x] Remove '...' from commercial software list; add links
- [x] Typos (cc>g&m>dimensionality title, author "biolgraphies" on who we are page)
- [x] Add author links wherever they're missing
- [x] Fix tutorial template new lines issue
- [x] Remove reference to knowledgebase being open source on user code page
- [x] Remove reference to applause button on intro page
- [x] Add UKAN logo (requested by Kirill)

**Comment by agully1** [comment]
[] add UKAN logo (requested by Kirill)

**Comment by agully1** [comment]
Authors still to be added to tutorials or format fixed

**Comment by mscroggs** [comment]
I've added authors in #121 and #119
