### ISSUE TITLE
Add a "who (we think) you are" page

### ISSUE THREAD

**Issue by agully1** [ca-knowledgebase/ca-knowledgebase.github.io#27]
Defining who we think the audience is, what we think they already know (and links to how to find it out if not)

**Comment by mscroggs** [comment]
Things we think the author already knows should include what we removed in this PR: https://github.com/ca-knowledgebase/ca-knowledgebase.github.io/pull/64

**Comment by mscroggs** [comment]
Suggestions:
- Not necessarily a computer science background
- From industry or academia (so might have different experiences)
- Users of commercial software that are interested in open software
- Have an aptitude for/knowledge of many of the basics of maths and waves/sound
- Someone who has an acoustics problem to solve and doesn't yet know how to solve it
