### ISSUE TITLE
CI with FEniCS

### ISSUE THREAD

**Issue by ca-knowledgebase** [ca-knowledgebase/ca-knowledgebase.github.io#3]
Currently the Jupyter Book auto builds when new md/notebook content is pushed to main, but this is more complicated with FEniCS leading to errors in the notebook compilation for the [first FEniCS tutorial](https://github.com/ca-knowledgebase/ca-knowledgebase.github.io/blob/main/tutorials/fenics-helmholtz-tutorial-1.ipynb).

Temporary solution: build locally with FEniCS installed

**Comment by jorgensd** [comment]
I would suggest we update the code to [FEniCSx](https://github.com/FEniCS/dolfinx) as it is the recommended version of the FEniCS project.

**Comment by jorgensd** [comment]
@mscroggs do we want to remove the old FEniCS tutorial now? It will be in git history if anyone is interested in it at a later stage.
