### ISSUE TITLE
Add an informative README

### ISSUE THREAD

**Issue by agully1** [ca-knowledgebase/ca-knowledgebase.github.io#8]

**Comment by mhamilt** [comment]
Some dove-tailing with #17 

Structure Suggestion:


- CA Knowledge base branding
- Table of Contents
- What is this
  - status  
  - link to the actual site
  - who is this for (the repo not the site)
- how to contact 
- how to contribute
  - how to clone
  - how to install Jupyter
    - do I need to in order to contribute? 
  - how to edit `.md`
  - how to edit `.ipynb`
  - how to edit `.yml`
  - flagging an issue 

Some of these might just link to other files in the repo
